getAllProducts:
    path:       /Products
    methods:    [GET]
    controller: App\Products\ProductsController\ProductsController::FindAll

getProductById:
    path:       /Products/{id}
    methods:    [GET]
    controller: App\Products\ProductsController\ProductsController::FindById

createProduct:
    path:       /Products
    methods:    [POST]
    controller: App\Products\ProductsController\ProductsController::Create

updateProduct:
    path:       /Products/{id}
    methods:    [PUT]
    controller: App\Products\ProductsController\ProductsController::Update

deleteProduct:
    path:       /Products/{id}
    methods:    [DELETE]
    controller: App\Products\ProductsController\ProductsController::Delete